// <auto-generated />
namespace BargainBarterV2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NoListOfBarterAds1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NoListOfBarterAds1));
        
        string IMigrationMetadata.Id
        {
            get { return "201610141310198_NoListOfBarterAds1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
